server.port=8080
spring.application.name=board-tarefas

# Serializar datas como ISO-8601 (ex: 2026-04-07T10:00:00)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
